{ lib, pkgs, username, ... }:

{
  config = {
    services.greetd = {
      enable = true;
      useTextGreeter = true;

      settings = {
        default_session = {
          # Taken from github:ryan4yin/nix-config.
          # .wayland-session is a script generated by home-manager, which links to the current wayland compositor(sway/hyprland or others).
          # with such a vendor-no-locking script, we can switch to another wayland compositor without modifying greetd's config here.
          #command = "${lib.getExe pkgs.tuigreet} --time --remember --cmd $HOME/.wayland-session";
          command = "${lib.getExe pkgs.tuigreet} --time --remember --remember-user-session";
          user = "${username}";
        };
      };
    };
  };
}
